"""
Bravix – AI Financial Analysis Route
------------------------------------
Handles incoming requests for AI-based financial report generation
using the GPT-5 and GPT-4o models.
"""

from fastapi import APIRouter, HTTPException, Request
from app.utils.analyze_with_chatgpt import analyze_with_chatgpt, get_openai_client

router = APIRouter()

@router.post("/analyze")
async def analyze_file(request: Request):
    """
    Accepts parsed financial data and performs AI-based financial risk analysis.
    """
    try:
        data = await request.json()
        raw_text = data.get("raw_text", "")
        indicators = data.get("indicators", {}) or {}

        print("🧠 Received AI analysis request.")
        print(f"📄 Raw text length: {len(raw_text)} | 📊 Indicators received: {len(indicators)}")

        # ✅ Initialize OpenAI client once (saves time if reused)
        client = get_openai_client()

        # ✅ Perform AI analysis
        result = analyze_with_chatgpt(raw_text, indicators, client=client)

        ai_text = result.get("analysis_raw", "No response generated by AI.")
        print(f"✅ AI analysis completed successfully. Output length: {len(ai_text)} characters")

        return {
            "status": "success",
            "message": "AI analysis complete",
            "ai_analysis": ai_text,
        }

    except ValueError as ve:
        # Handle missing API key or setup errors
        print(f"🚫 Configuration error: {ve}")
        raise HTTPException(status_code=500, detail=str(ve))

    except Exception as e:
        print(f"❌ AI analysis failed: {e}")
        raise HTTPException(status_code=500, detail=f"AI analysis failed: {e}")
