"""
Bravix – Unified Report Generation & PDF Download (v4.0)
--------------------------------------------------------
Aligned with new AI + ratio engine structure.
Uses safe ASCII sanitization (no Unicode fonts required).
"""

import os, json, datetime, re
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from fpdf import FPDF

router = APIRouter()
TMP_PATH = "/tmp/last_analysis.json"
PDF_PATH = "/tmp/report.pdf"

# --------------------------------------------------------------
# 🧩 Safe PDF Template (Helvetica only)
# --------------------------------------------------------------
class PDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.cell(0, 10, "Braivix Credit Evaluation Report", ln=True, align="C")
        self.set_font("Helvetica", "I", 9)
        self.cell(0, 8, "AI-Driven Financial Analysis & Credit Classification", ln=True, align="C")
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Braivix", align="C")

# --------------------------------------------------------------
# 🔧 Sanitization Helper
# --------------------------------------------------------------
def sanitize_text(text: str) -> str:
    """Replace fancy punctuation and symbols with ASCII-safe versions."""
    if not text:
        return ""
    replacements = {
        "’": "'", "‘": "'", "‛": "'", "´": "'", "`": "'",
        "“": '"', "”": '"', "„": '"', "‟": '"',
        "–": "-", "—": "-", "―": "-", "•": "-", "°": " deg",
        "…": "...", "→": "->", "←": "<-", "©": "(c)", "®": "(R)", "™": "(TM)",
        "·": "-", "▪": "-", "−": "-", "—": "-",
        " ": " ", " ": " ",  # non-breaking spaces
    }
    for bad, good in replacements.items():
        text = text.replace(bad, good)
    # Remove any non-ASCII leftovers
    text = re.sub(r"[^\x00-\x7F]+", "", text)
    return text.strip()

# --------------------------------------------------------------
# 📄 PDF Generation Endpoint
# --------------------------------------------------------------
@router.get("/report/download")
def download_report():
    """Generate and return the latest AI report as a downloadable PDF."""
    if not os.path.exists(TMP_PATH):
        raise HTTPException(status_code=404, detail="No report found. Please analyze a file first.")

    with open(TMP_PATH, "r") as f:
        data = json.load(f)

    # --- Extract unified fields ---
    structured = data.get("structured_report", {})
    classification = data.get("classification", {})
    indicators = data.get("indicators", [])
    summary = sanitize_text(structured.get("summary") or data.get("ai_report") or "No summary available.")
    overall_score = data.get("overall_health_score", "N/A")

    company = sanitize_text(data.get("data", {}).get("company_name") or "Unknown_Company")
    company_class = sanitize_text(classification.get("company_class", "N/A"))
    risk = sanitize_text(classification.get("risk_category", "N/A"))
    decision = sanitize_text(classification.get("credit_decision", "N/A"))
    ratings = classification.get("ratings", {"Moodys": "N/A", "S&P": "N/A"})

    # ---------------------- Generate PDF ----------------------
    pdf = PDF()
    pdf.add_page()

    # --- Header Section ---
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, f"Company: {company}", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Date: {datetime.date.today()}", ln=True)
    pdf.cell(0, 8, f"Company Class: {company_class}", ln=True)
    pdf.cell(0, 8, f"Overall Health Score: {overall_score}", ln=True)
    pdf.cell(0, 8, f"Risk Category: {risk}", ln=True)
    pdf.cell(0, 8, f"Credit Decision: {decision}", ln=True)
    pdf.cell(0, 8, f"Moodys Rating: {sanitize_text(ratings.get('Moodys', 'N/A'))}", ln=True)
    pdf.cell(0, 8, f"S&P Rating: {sanitize_text(ratings.get('S&P', 'N/A'))}", ln=True)
    pdf.ln(8)

    # --- Summary Section ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "AI Summary", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 8, summary)
    pdf.ln(8)

    # --- Indicators Section ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Financial Indicators", ln=True)
    pdf.set_font("Helvetica", "", 10)
    if not indicators:
        pdf.cell(0, 7, "No indicators available.", ln=True)
    else:
        for item in indicators:
            name = sanitize_text(item.get("name", "Unknown"))
            value = item.get("value", "N/A")
            status = sanitize_text(item.get("status", "N/A"))
            pdf.cell(0, 7, f"{name}: {value} ({status})", ln=True)

    # --- Ratings Key ---
    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Rating Key (for reference)", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(
        0,
        7,
        sanitize_text("""A -> Moody's: Aaa–A2 | S&P: AAA–A  -> Excellent
B -> Moody's: Baa1–Baa3 | S&P: BBB+ -> Good
C -> Moody's: Ba1–Ba3 | S&P: BB -> Average
D -> Moody's: B1–B3 | S&P: B -> Weak
E -> Moody's: Caa–C | S&P: CCC–D -> Critical"""),
    )

    # --- Save PDF ---
    pdf.output(PDF_PATH)

    clean_name = "".join(c if c.isalnum() else "_" for c in company)[:30]
    filename = f"{clean_name}_Report_{datetime.date.today()}.pdf"

    return FileResponse(
        PDF_PATH,
        filename=filename,
        media_type="application/pdf",
        headers={"Cache-Control": "no-store", "Access-Control-Allow-Origin": "*"},
    )
